// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest
// DO NOT EDIT. ANY CHANGES WILL BE LOST

#ifndef NGREST_EXAMPLES_ECHOWRAPPER_H
#define NGREST_EXAMPLES_ECHOWRAPPER_H

#include <string>

#include <ngrest/engine/ServiceWrapper.h>
#include "Echo.h"


namespace ngrest {
namespace examples {


class Echo;

//! Echo service wrapper
class EchoWrapper: public ::ngrest::ServiceWrapper
{
public:
    EchoWrapper();
    virtual ~EchoWrapper();

    virtual ::ngrest::Service* getServiceImpl() override;

    virtual void invoke(const ::ngrest::OperationDescription* operation, ::ngrest::MessageContext* context) override;

    virtual const ::ngrest::ServiceDescription* getDescription() const override;

private:
    Echo* service;
};



}
}


#endif // NGREST_EXAMPLES_ECHOWRAPPER_H

