// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest
// DO NOT EDIT. ANY CHANGES WILL BE LOST

#ifndef NGREST_EXAMPLES_CRUDWRAPPER_H
#define NGREST_EXAMPLES_CRUDWRAPPER_H

#include <string>

#include <ngrest/engine/ServiceWrapper.h>
#include "Crud.h"


namespace ngrest {
namespace examples {


class Crud;

//! Crud service wrapper
class CrudWrapper: public ::ngrest::ServiceWrapper
{
public:
    CrudWrapper();
    virtual ~CrudWrapper();

    virtual ::ngrest::Service* getServiceImpl() override;

    virtual void invoke(const ::ngrest::OperationDescription* operation, ::ngrest::MessageContext* context) override;

    virtual const ::ngrest::ServiceDescription* getDescription() const override;

private:
    Crud* service;
};



}
}


#endif // NGREST_EXAMPLES_CRUDWRAPPER_H

