// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest
// DO NOT EDIT. ANY CHANGES WILL BE LOST

#ifndef NGREST_FAVICONWRAPPER_H
#define NGREST_FAVICONWRAPPER_H

#include <string>

#include <ngrest/engine/ServiceWrapper.h>
#include "Favicon.h"


namespace ngrest {


class Favicon;

//! Favicon service wrapper
class FaviconWrapper: public ::ngrest::ServiceWrapper
{
public:
    FaviconWrapper();
    virtual ~FaviconWrapper();

    virtual ::ngrest::Service* getServiceImpl() override;

    virtual void invoke(const ::ngrest::OperationDescription* operation, ::ngrest::MessageContext* context) override;

    virtual const ::ngrest::ServiceDescription* getDescription() const override;

private:
    Favicon* service;
};



}


#endif // NGREST_FAVICONWRAPPER_H

