// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest
// DO NOT EDIT. ANY CHANGES WILL BE LOST

#include <ngrest/utils/Log.h>
#include <ngrest/utils/fromcstring.h>
#include <ngrest/utils/tostring.h>
#include <ngrest/utils/Exception.h>
#include <ngrest/common/ObjectModel.h>
#include <ngrest/common/ObjectModelUtils.h>
#include <ngrest/common/Message.h>
#include <ngrest/common/HttpMethod.h>
#include <ngrest/common/Service.h>
#include <ngrest/engine/ServiceDescription.h>
#include "FaviconWrapper.h"



namespace ngrest {


FaviconWrapper::FaviconWrapper():
    service(new Favicon())
{
}

FaviconWrapper::~FaviconWrapper()
{
    delete service;
}


::ngrest::Service* FaviconWrapper::getServiceImpl()
{
    return service;
}

void FaviconWrapper::invoke(const ::ngrest::OperationDescription* operation, ::ngrest::MessageContext* context)
{
    if (operation->name == "favicon") {   //  **************** favicon *****************

        /// void favicon(MessageContext& context);

/// ######### deserialize request ###########


/// ######### deserialize request end ###########

        service->favicon(*context);

        context->callback->success();
    } else {
        NGREST_THROW_ASSERT("No operation " + operation->name + " found in service Favicon");
    }
}

const ::ngrest::ServiceDescription* FaviconWrapper::getDescription() const
{
    static ::ngrest::ServiceDescription description = {
        "ngrest.Favicon", // name
        "favicon.ico", // location
        R"(Simple service to display favicon in browser)", // description
        R"()", // details
        {
            {
                "favicon",             // name
                "/", // location
                static_cast<int>(::ngrest::HttpMethod::GET),
                "GET",
                false,
                R"()", // description
                R"()", // details
                {

                },
                ::ngrest::ParameterDescription::Type::Undefined, false
            }
        }
    };

    return &description;
}


}

